import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'stretch',
    justifyContent: 'center',
  },

  // Formulário de Autenticação (Cadastro e Login)
  bg: {
    flex: 1,
    backgroundColor: "#81C784",
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    width: "80%",
    maxWidth: 400,
    backgroundColor: "#fff",
    borderRadius: 28,
    overflow: "hidden",
    alignItems: "center",
    marginVertical: 32,
  },
  header: {
    width: "100%",
    paddingVertical: 24,
    alignItems: "center",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  tituloAutenticacao: {
    color: "#fff",
    fontSize: 22,
    letterSpacing: 1,
    fontFamily: "Poppins_700Bold",
  },
  form: {
    width: "100%",
    padding: 24,
    alignItems: "center",
  },
  inputAutenticacao: {
    width: "100%",
    backgroundColor: "#ECECEC",
    borderRadius: 12,
    padding: 14,
    marginBottom: 18,
    fontSize: 16,
    color: "#222",
    fontFamily: "Inter_400Regular", 
    minHeight: 50,
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  button: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 12,
    backgroundColor: "#1E88E5",
  },
  buttonTextAutenticacao: {
    color: "#fff",
    fontSize: 18,
    letterSpacing: 1,
    fontFamily: "Inter_700Bold",
  },

  // Formulário de Informações do Abrigo
  cardInfo: {
    width: "80%",
    maxWidth: 420,
    height: 650,
    backgroundColor: "#fff",
    borderRadius: 28,
    overflow: "hidden",
    alignItems: "center",
    marginVertical: 32,
  },
  headerInfo: {
    width: "100%",
    paddingVertical: 24,
    alignItems: "center",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  tituloInfo: {
    color: "#fff",
    fontSize: 22,
    letterSpacing: 1,
    fontFamily: "Poppins_700Bold",
  },
  formInfo: {
    width: "100%",
    alignItems: "center",
    padding: 24,
    paddingBottom: 40,
  },
  inputInfo: {
    width: "100%",
    backgroundColor: "#ECECEC",
    borderRadius: 12,
    padding: 16,
    marginVertical: 12,
    fontSize: 16,
    color: "#222",
    fontFamily: "Inter_400Regular",
  },
  addLink: {
    color: "#1E88E5",
    fontSize: 15,
    marginBottom: 30,
    fontFamily: "Inter_500Medium",
  },
  buttonInfo: {
    width: "100%",
    backgroundColor: "#1E88E5",
    borderRadius: 16,
    alignItems: "center",
    paddingVertical: 16,
    marginTop: 12,
    marginBottom: 8,
  },
  buttonTextInfo: {
    color: "#fff",
    fontSize: 22,
    letterSpacing: 1,
    fontFamily: "Inter_700Bold",
  },

  // Dashboard
  bgDashboard: {
    backgroundColor: "#81C784",
    alignItems: "center",
    paddingTop: 32,
  },
  logoRow: {
    flexDirection: "row",
    marginBottom: 18,
    marginTop: 10,
    gap: 10,
  },
  logoImg: {
    width: 48,
    height: 48,
    marginRight: 8,
  },
  logoText: {
    fontSize: 36,
    fontFamily: "Poppins_900Black",
    letterSpacing: 1,
  },
  logoSafe: {
    color: "#fff",
    fontFamily: "Poppins_900Black",
  },
  logoBoard: {
    color: "#1E88E5",
    fontFamily: "Poppins_900Black",
  },
  resourcesRow: {
    flexDirection: "row",
    justifyContent: "center",
    width: "90%",
    marginBottom: 10,
    gap: 16,
  },
  resourceBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E88E5",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 12,
    marginHorizontal: 4,
    minWidth: 140,
    elevation: 2,
    gap: 12,
  },
  resourceIcon: {
    width: 38,
    height: 38,
    marginRight: 8,
  },
  resourceLabel: {
    color: "#dbeafe",
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    marginBottom: 2,
  },
  resourceValue: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Inter_400Regular",
  },
  bold: {
    fontFamily: "Inter_700Bold",
  },
  resourceUnit: {
    color: "#f9f9f9",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  peopleCard: {
    width: "90%",
    marginTop: 18,
    marginBottom: 18,
    padding: 0,
    overflow: "hidden",
    elevation: 2,
  },
  peopleTitle: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Inter_400Regular", 
    padding: 16,
    paddingBottom: 8,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: "transparent",
  },
  peopleGauge: {
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
  },
  gaugeArc: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    position: "relative",
  },
  gaugeImg: {
    width: 170,
    height: 80,
    marginBottom: -40,
  },
  peopleNumber: {
    color: "#fff",
    fontSize: 40,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    position: "absolute",
    left: 0,
    right: 0,
    top: 32,
  },
  gaugeLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginTop: 4,
  },
  gaugeLabel: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Inter_400Regular",
    opacity: 0.8,
  },
  alert: {
    fontFamily: "Inter_700Bold",
    marginTop: 12,
    textAlign: 'center',
    fontSize: 16,
  },
  mapPlaceholder: {
    width: "90%",
    aspectRatio: 1,
    backgroundColor: "#c8e6c9",
    borderRadius: 24,
    marginTop: 16,
    marginBottom: 36,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  mapImg: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
  },

  //Landing Page
  containerLanding: {
    flex: 1,
    backgroundColor: '#8ED18A',
    padding: 0,
    alignItems: 'center',
  },
  headerLanding: {
    width: '100%',
    marginTop: 30,
    marginBottom: 20,
    alignItems: 'center',
  },
  logoRowLanding: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
    marginLeft: 30,
    alignSelf: 'flex-start',
  },
  logoIcon: {
    width: 40,
    height: 52,
    marginRight: 8,
  },
  logoTextLanding: {
    fontFamily: 'Poppins_900Black',
    fontSize: 28,
    color: 'white',
    letterSpacing: 1,
  },
  infoRow: {
    flexDirection: 'row',
  },
  mobileImg: {
    width: 200,
    height: 320,
    resizeMode: 'contain',
    borderRadius: 18,
  },
  infoText: {
    flex: 1,
    fontFamily: 'Inter_900Black',
    fontSize: 16,
    color: 'white',
    lineHeight: 22,
  },
  cardLanding: {
    width: '90%',
    borderRadius: 18,
    padding: 20,
    marginTop: 30,
    alignItems: 'flex-start',
    position: 'relative',
    minHeight: 180,
  },
  cardTitle: {
    fontFamily: 'Inter_900Black',
    fontSize: 20,
    color: 'white',
    marginBottom: 16,
    width: '70%',
  },
  cardImg: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 210,
    height: 250,
    resizeMode: 'contain',
  },
  buttonLanding: {
    marginTop: 18,
    backgroundColor: 'white',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  buttonText: {
    color: '#1E88E5',
    fontFamily: 'Inter_900Black',
    fontSize: 16,
    fontWeight: '900',
  },

  // Configurações
  cardCondig: {
    width: "92%",
    borderRadius: 18,
    backgroundColor: "#fff",
    marginTop: 40,
    marginBottom: 20,
    overflow: "hidden",
    elevation: 4,
  },
  headerConfig: {
    width: "100%",
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  tituloConfig: {
    color: "#fff",
    fontSize: 24,
    fontFamily: "Poppins_900Black",
    letterSpacing: 1,
  },
  formConfig: {
    padding: 20,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  labelConfig: {
    fontSize: 16,
    color: "#1E88E5",
    fontFamily: "Inter_700Bold",
    marginBottom: 4,
    marginTop: 10,
  },
  inputConfig: {
    borderWidth: 1,
    borderColor: "#B9B6B6",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    fontSize: 16,
    color: "#222",
    backgroundColor: "#F7F7F7",
    fontFamily: "Inter_400Regular",
  },

  // Mapa
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  legendaContainer: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    padding: 10,
    zIndex: 10,
    elevation: 10,
    minWidth: 140,
  },
  legendaOverlay: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 6,
    minWidth: 110,
    zIndex: 20,
  },
  legendaTitulo: {
    fontWeight: 'bold',
    marginBottom: 6,
    fontSize: 15,
    color: '#1E88E5',
    letterSpacing: 0.5,
  },
  legendaItens: {
    flexDirection: 'column',
    gap: 6,
  },
  legendaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  diamante: {
    width: 16,
    height: 16,
    marginRight: 7,
    transform: [{ rotate: '45deg' }],
    borderWidth: 1,
    borderColor: '#888',
  },
  legendaTexto: {
    fontSize: 13,
    color: '#333',
  },
});

export { styles };
